version: '3.8'

services:
  backend:
    build: ./backend
    container_name: allia-backend
    ports:
      - "3001:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: allia-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
